# Generated by Django 3.2.18 on 2023-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='content',
            field=models.TextField(default='No Details'),
        ),
    ]
