# Generated by Django 3.2.18 on 2023-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_vehiclemodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='slug',
            field=models.SlugField(default='my-default-slug'),
        ),
    ]
