# Generated by Django 3.2.18 on 2023-04-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_vehiclemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='slug',
        ),
    ]
