# Generated by Django 3.2.18 on 2023-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_vehiclemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
